apiVersion: v1
kind: ConfigMap
metadata:
  name: connection-parameters
data:
  db_host: dev.host.local
  db_user: dev.user
  db_pass: dev.pass
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: contenedor1
          image: nginx:alpine
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: connection-parameters
                  key: db_host
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: connection-parameters
                  key: db_user
            - name: DB_PASS
              valueFrom:
                configMapKeyRef:
                  name: connection-parameters
                  key: db_pass
