apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend1-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend1-app
  template:
    metadata:
      labels:
        app: backend1-app
    spec:
      containers:
        - name: backend1-container
          image: localhost:5000/backend1-ms
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: SERVICE_BACKEND2
              value: "http://backend2-svc/api/message"
