apiVersion: v1
kind: Pod
metadata:
  name: memory-demo-cpu
spec:
  containers:
    - name: cpu-demo
      image: vish/stress
      resources:
        limits:
          cpu: "100"
        requests:
          cpu: "100"
      args:
        - -cpus
        - "2"
