version: "3.8"

services:
  mysql-service:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: db_curso
      MYSQL_USER: shidalgo
      MYSQL_PASSWORD: 12345
    ports:
      - 3306:3306
    volumes:
      - mysql-vol:/var/lib/mysql
    networks:
      - wordpress-net

  wordpress-service:
    image: wordpress:6
    container_name: wordpress-container
    environment:
      WORDPRESS_DB_HOST: mysql-service
      WORDPRESS_DB_USER: shidalgo
      WORDPRESS_DB_PASSWORD: 12345
      WORDPRESS_DB_NAME: db_curso
    ports:
      - 8080:80
    volumes:
      - wordpress-vol:/var/www/html
    networks:
      - wordpress-net
    depends_on:
      - mysql-service

volumes:
  mysql-vol:
    name: mysql-vol
  wordpress-vol:
    name: wordpress-vol

networks:
  wordpress-net:
    name: wordpress-net
