apiVersion: v1
kind: Namespace
metadata:
  name: nsp-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dev-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-pods
subjects:
  - kind: Group
    name: cursosdev
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: dev-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: server-nginx
  namespace: nsp-dev
spec:
  containers:
    - name: web
      image: nginx:alpine
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: connection-parameters
  namespace: nsp-dev
data:
  db_host: dev.host.local
  db_user: dev.user
  db_pass: dev.pass
