apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: LimitRange
metadata:
  name: min-max-memory-cpu
  namespace: dev
spec:
  limits:
    - max:
        memory: 1Gi
        cpu: 1
      min:
        memory: 100M
        cpu: 100m
      type: Container
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-limits
  namespace: dev
spec:
  containers:
    - name: nginx-server
      image: nginx:alpine
      resources:
        limits:
          memory: 512Mi
          cpu: 500m
